[project]
name = "edf-iron-core"
readme = "README.md"
license = "MIT"
license-files = ["LICENSE"]
keywords = ["edf", "iron", "core"]
description = "EDF Iron Core"
requires-python = ">=3.12"
dynamic = ["version"]
authors = [
  { name="CERT-EDF", email="cert@edf.fr" },
]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Topic :: Utilities",
    "Topic :: Security",
]
dependencies = [
    "edf-fusion~=3.0",
]


[project.urls]
"Homepage" = "https://github.com/cert-edf/iron"
"Repository" = "https://github.com/cert-edf/iron"
"Bug Tracker" = "https://github.com/cert-edf/iron/issues"


[build-system]
requires = ["setuptools>=83", "setuptools_scm>=10", "wheel"]
build-backend = "setuptools.build_meta"


[tool.setuptools.packages.find]
where = ["."]
include = ["edf_iron_core", "edf_iron_core.*"]


[tool.setuptools_scm]
root = ".."
version_file = "edf_iron_core/__version__.py"


[tool.ruff]
include = ["pyproject.toml", "edf_iron_core/**/*.py"]
exclude = ["edf_iron_core/__version__.py"]
line-length = 79


[tool.ruff.format]
quote-style = "preserve"
